### ISSUE TITLE
Will these paragraphs fixes go into the Drupal.org project? 

### ISSUE THREAD

**Issue by 4aficiona2** [AmazeeLabs/paragraphs#1]
It seems that the paragraphs module for D8 gets developed / maintained here on Github. My question: will the changes / fixes / enhancements from here find there way into the [Drupal.org Module](https://www.drupal.org/node/2411033) or do they live seperatly?

Do you recommend to use the D8 Github version over the D8 Drupal.org version for multilang sites?

**Comment by Leksat** [comment]
@4aficiona2 this is just a fork, it's better to use official repository http://drupal.org/project/paragraphs
